package org.anticensor.vpn.core.tunnel

import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets

/**
 * Model and YAML configuration generator for hev-socks5-tunnel.
 * Generates valid YAML configuration files consumed by the native C tun2socks engine.
 */
data class HevTunnelConfig(
    val tunnel: TunnelSection = TunnelSection(),
    val socks5: Socks5Section = Socks5Section(),
    val misc: MiscSection = MiscSection()
) {
    data class TunnelSection(
        val name: String = "tun0",
        val mtu: Int = 1500,
        val ipv4: String = "172.19.0.1",
        val ipv6: String = "fdfe:dcba:9876::1"
    )

    data class Socks5Section(
        val port: Int = 10808,
        val address: String = "127.0.0.1",
        val udp: String = "udp", // "udp" or "tcp"
        val username: String = "",
        val password: String = "",
        val mark: Int = 0 // SO_MARK fwmark to bypass routing loops
    )

    data class MiscSection(
        val taskStackSize: Int = 81920,   // 80KB coroutine fiber stack
        val connectTimeout: Int = 5000,   // Milliseconds
        val readWriteTimeout: Int = 60000,// Milliseconds
        val limitNofile: Int = 65535,     // File descriptor rlimit
        val logLevel: String = "warn"     // "debug" | "info" | "warn" | "error"
    )

    /**
     * Serializes this configuration to standard YAML format required by hev-socks5-tunnel.
     */
    fun toYaml(): String {
        val sb = StringBuilder()
        sb.append("# Generated by AegisVPN Engine (Phase 2)\n")
        sb.append("# hev-socks5-tunnel configuration\n\n")

        sb.append("tunnel:\n")
        sb.append("  name: ${tunnel.name}\n")
        sb.append("  mtu: ${tunnel.mtu}\n")
        sb.append("  ipv4: ${tunnel.ipv4}\n")
        sb.append("  ipv6: '${tunnel.ipv6}'\n\n")

        sb.append("socks5:\n")
        sb.append("  port: ${socks5.port}\n")
        sb.append("  address: ${socks5.address}\n")
        sb.append("  udp: '${socks5.udp}'\n")
        if (socks5.username.isNotBlank()) {
            sb.append("  username: '${socks5.username}'\n")
        }
        if (socks5.password.isNotBlank()) {
            sb.append("  password: '${socks5.password}'\n")
        }
        if (socks5.mark > 0) {
            sb.append("  mark: ${socks5.mark}\n")
        }
        sb.append("\n")

        sb.append("misc:\n")
        sb.append("  task-stack-size: ${misc.taskStackSize}\n")
        sb.append("  connect-timeout: ${misc.connectTimeout}\n")
        sb.append("  read-write-timeout: ${misc.readWriteTimeout}\n")
        sb.append("  limit-nofile: ${misc.limitNofile}\n")
        sb.append("  log-level: '${misc.logLevel}'\n")

        return sb.toString()
    }

    /**
     * Writes the YAML configuration to the specified destination file atomically.
     */
    fun writeToFile(targetFile: File) {
        val tempFile = File(targetFile.parentFile, "${targetFile.name}.tmp")
        OutputStreamWriter(FileOutputStream(tempFile), StandardCharsets.UTF_8).use { writer ->
            writer.write(toYaml())
            writer.flush()
        }
        if (!tempFile.renameTo(targetFile)) {
            tempFile.copyTo(targetFile, overwrite = true)
            tempFile.delete()
        }
    }

    /**
     * Validates configuration parameters against safety and protocol constraints.
     */
    fun validate(): Result<Unit> {
        if (tunnel.mtu < 576 || tunnel.mtu > 9000) {
            return Result.failure(IllegalArgumentException("MTU must be between 576 and 9000 bytes (was ${tunnel.mtu})"))
        }
        if (socks5.port !in 1..65535) {
            return Result.failure(IllegalArgumentException("SOCKS5 port must be in range 1..65535 (was ${socks5.port})"))
        }
        if (misc.taskStackSize < 16384) {
            return Result.failure(IllegalArgumentException("Task stack size too small, minimum 16384 bytes required"))
        }
        return Result.success(Unit)
    }

    companion object {
        /**
         * Standard configuration preset targeting local SOCKS5 proxy on port 10808.
         */
        fun default(port: Int = 10808, mtu: Int = 1500): HevTunnelConfig {
            return HevTunnelConfig(
                tunnel = TunnelSection(mtu = mtu),
                socks5 = Socks5Section(port = port)
            )
        }

        /**
         * Gaming/interactive low-latency preset with smaller stack and short connection timeouts.
         */
        fun lowLatency(port: Int = 10808): HevTunnelConfig {
            return HevTunnelConfig(
                tunnel = TunnelSection(mtu = 1420),
                socks5 = Socks5Section(port = port),
                misc = MiscSection(
                    taskStackSize = 40960,
                    connectTimeout = 3000,
                    readWriteTimeout = 30000,
                    logLevel = "warn"
                )
            )
        }

        /**
         * High-throughput preset for video streaming or bulk downloads.
         */
        fun highThroughput(port: Int = 10808): HevTunnelConfig {
            return HevTunnelConfig(
                tunnel = TunnelSection(mtu = 1500),
                socks5 = Socks5Section(port = port),
                misc = MiscSection(
                    taskStackSize = 131072, // 128KB
                    connectTimeout = 6000,
                    readWriteTimeout = 120000,
                    limitNofile = 100000,
                    logLevel = "error"
                )
            )
        }
    }
}
