import React, { useState, useEffect } from 'react';
import {
  Cpu,
  Settings2,
  Download,
  Copy,
  Check,
  Play,
  Square,
  Activity,
  ArrowRight,
  ShieldCheck,
  AlertTriangle,
  FileCode,
  Terminal,
  Zap
} from 'lucide-react';

export const Phase2TunnelLab: React.FC = () => {
  // Config state
  const [tunnelName, setTunnelName] = useState('tun0');
  const [mtu, setMtu] = useState(1500);
  const [ipv4, setIpv4] = useState('172.19.0.1');
  const [ipv6, setIpv6] = useState('fdfe:dcba:9876::1');

  const [socks5Port, setSocks5Port] = useState(10808);
  const [socks5Address, setSocks5Address] = useState('127.0.0.1');
  const [socks5Udp, setSocks5Udp] = useState<'udp' | 'tcp'>('udp');
  const [socks5Mark, setSocks5Mark] = useState(0);

  const [stackSize, setStackSize] = useState(81920);
  const [connectTimeout, setConnectTimeout] = useState(5000);
  const [rwTimeout, setRwTimeout] = useState(60000);
  const [limitNofile, setLimitNofile] = useState(65535);
  const [logLevel, setLogLevel] = useState<'debug' | 'info' | 'warn' | 'error'>('warn');

  const [copied, setCopied] = useState(false);

  // Live simulation state
  const [isRunning, setIsRunning] = useState(false);
  const [simTxBytes, setSimTxBytes] = useState(104857600); // 100MB
  const [simRxBytes, setSimRxBytes] = useState(256901120); // 245MB
  const [txSpeed, setTxSpeed] = useState(1450000); // 1.45 MB/s
  const [rxSpeed, setRxSpeed] = useState(8900000); // 8.9 MB/s
  const [activeSessions, setActiveSessions] = useState(14);
  const [logs, setLogs] = useState<string[]>([
    '[HevTunnelBridge] JNI libhev-socks5-tunnel.so initialized',
    '[HevTunnelConfig] Parsed YAML config: SOCKS5 127.0.0.1:10808, MTU 1500',
    '[HevTaskSystem] Cooperative task epoll reactor ready',
    '[HevTunnelCore] TUN device fd=48 bound to hev-socks5-tunnel'
  ]);

  // Presets
  const applyPreset = (type: 'default' | 'gaming' | 'streaming') => {
    if (type === 'default') {
      setMtu(1500);
      setSocks5Port(10808);
      setStackSize(81920);
      setConnectTimeout(5000);
      setRwTimeout(60000);
      setLimitNofile(65535);
      setLogLevel('warn');
    } else if (type === 'gaming') {
      setMtu(1420);
      setSocks5Port(10808);
      setStackSize(40960);
      setConnectTimeout(2500);
      setRwTimeout(30000);
      setLimitNofile(32768);
      setLogLevel('warn');
    } else if (type === 'streaming') {
      setMtu(1500);
      setSocks5Port(10808);
      setStackSize(131072);
      setConnectTimeout(6000);
      setRwTimeout(120000);
      setLimitNofile(100000);
      setLogLevel('error');
    }
  };

  // Generate YAML string
  const yamlContent = `# Generated by AegisVPN Engine (Phase 2)
# hev-socks5-tunnel YAML specification
tunnel:
  name: ${tunnelName}
  mtu: ${mtu}
  ipv4: ${ipv4}
  ipv6: '${ipv6}'

socks5:
  port: ${socks5Port}
  address: ${socks5Address}
  udp: '${socks5Udp}'${socks5Mark > 0 ? `\n  mark: ${socks5Mark}` : ''}

misc:
  task-stack-size: ${stackSize}
  connect-timeout: ${connectTimeout}
  read-write-timeout: ${rwTimeout}
  limit-nofile: ${limitNofile}
  log-level: '${logLevel}'`;

  // Validation
  const isValidMtu = mtu >= 576 && mtu <= 9000;
  const isValidPort = socks5Port >= 1024 && socks5Port <= 65535;
  const isValidConfig = isValidMtu && isValidPort;

  // Simulator tick
  useEffect(() => {
    if (!isRunning) return;
    const interval = setInterval(() => {
      const deltaTx = Math.floor(Math.random() * 800000) + 400000;
      const deltaRx = Math.floor(Math.random() * 4500000) + 2000000;
      setSimTxBytes(prev => prev + deltaTx);
      setSimRxBytes(prev => prev + deltaRx);
      setTxSpeed(deltaTx);
      setRxSpeed(deltaRx);
      setActiveSessions(prev => Math.max(4, Math.min(32, prev + (Math.random() > 0.5 ? 1 : -1))));

      if (Math.random() > 0.6) {
        const sampleLogs = [
          `[HevTunnelCore] TCP socket spliced to 127.0.0.1:${socks5Port} [CONNECT 104.244.42.1:443]`,
          `[HevTunnelCore] UDP ASSOCIATE datagram forwarded: 1420 bytes`,
          `[HevTaskSystem] Fiber coroutine yielded, epoll events matched: 2`,
          `[HevTunnelCore] Zero-copy buffer flushed to TUN device`
        ];
        const newLog = sampleLogs[Math.floor(Math.random() * sampleLogs.length)];
        setLogs(prev => [...prev.slice(-12), newLog]);
      }
    }, 1000);
    return () => clearInterval(interval);
  }, [isRunning, socks5Port]);

  const handleCopyYaml = () => {
    navigator.clipboard.writeText(yamlContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadYaml = () => {
    const blob = new Blob([yamlContent], { type: 'text/yaml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'hev_tunnel_config.yaml';
    a.click();
    URL.revokeObjectURL(url);
  };

  const formatBytes = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1048576) return `${(bytes / 1024).toFixed(1)} KB`;
    if (bytes < 1073741824) return `${(bytes / 1048576).toFixed(1)} MB`;
    return `${(bytes / 1073741824).toFixed(2)} GB`;
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-cyan-950/40 to-slate-900 border border-cyan-500/30 rounded-2xl p-6 shadow-xl">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold uppercase bg-cyan-500/15 text-cyan-400 border border-cyan-500/30">
                Phase 2 Delivered
              </span>
              <span className="text-slate-500">•</span>
              <span className="text-xs font-mono text-slate-400">Native NDK tun2socks Engine</span>
            </div>
            <h2 className="text-xl font-bold text-white tracking-tight flex items-center gap-2">
              <Cpu className="w-5 h-5 text-cyan-400" />
              hev-socks5-tunnel & JNI Integration Lab
            </h2>
            <p className="text-xs text-slate-300 mt-1 max-w-3xl leading-relaxed">
              Complete C11 coroutine architecture routing Linux TUN packets into local SOCKS5 daemons.
              Zero Go runtime overhead (&lt;5MB RAM), epoll multiplexing, live byte polling, and YAML config generation.
            </p>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => setIsRunning(!isRunning)}
              className={`flex items-center gap-2 px-4 py-2 rounded-xl text-xs font-bold font-mono transition-all shadow-md ${
                isRunning
                  ? 'bg-rose-600 hover:bg-rose-500 text-white shadow-rose-600/20'
                  : 'bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-400 hover:to-blue-500 text-slate-950 shadow-cyan-500/20'
              }`}
            >
              {isRunning ? (
                <>
                  <Square className="w-3.5 h-3.5" />
                  Halt Tunnel Loop
                </>
              ) : (
                <>
                  <Play className="w-3.5 h-3.5 fill-current" />
                  Simulate Native Engine
                </>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Real-time Tunnel Monitor */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-1">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span>Download Throughput</span>
            <Activity className={`w-3.5 h-3.5 ${isRunning ? 'text-emerald-400 animate-pulse' : 'text-slate-600'}`} />
          </div>
          <div className="text-xl font-bold text-white font-mono">
            {isRunning ? `${(rxSpeed / 1048576).toFixed(2)} MB/s` : '0.00 MB/s'}
          </div>
          <div className="text-[11px] text-slate-500 font-mono">
            Total RX: {formatBytes(simRxBytes)}
          </div>
        </div>

        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-1">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span>Upload Throughput</span>
            <Activity className={`w-3.5 h-3.5 ${isRunning ? 'text-cyan-400 animate-pulse' : 'text-slate-600'}`} />
          </div>
          <div className="text-xl font-bold text-white font-mono">
            {isRunning ? `${(txSpeed / 1048576).toFixed(2)} MB/s` : '0.00 MB/s'}
          </div>
          <div className="text-[11px] text-slate-500 font-mono">
            Total TX: {formatBytes(simTxBytes)}
          </div>
        </div>

        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-1">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span>Active Coroutine Fibers</span>
            <Zap className="w-3.5 h-3.5 text-amber-400" />
          </div>
          <div className="text-xl font-bold text-white font-mono">
            {isRunning ? `${activeSessions} sessions` : 'Idle'}
          </div>
          <div className="text-[11px] text-slate-500 font-mono">
            Stack: {stackSize / 1024} KB / task
          </div>
        </div>

        <div className="p-4 rounded-xl bg-slate-900/80 border border-slate-800 space-y-1">
          <div className="flex items-center justify-between text-xs font-mono text-slate-400">
            <span>Tunnel Status</span>
            <span className={`w-2 h-2 rounded-full ${isRunning ? 'bg-emerald-400 animate-ping' : 'bg-slate-600'}`} />
          </div>
          <div className="text-base font-bold text-white font-mono">
            {isRunning ? 'TUN FD=48 ESTABLISHED' : 'STOPPED'}
          </div>
          <div className="text-[11px] text-slate-500 font-mono">
            Target: {socks5Address}:{socks5Port}
          </div>
        </div>
      </div>

      {/* Main Grid: Configurator on Left, Live YAML & Logs on Right */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left: Configuration Form */}
        <div className="lg:col-span-6 bg-slate-900 border border-slate-800 rounded-xl p-5 space-y-5">
          <div className="flex items-center justify-between pb-3 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <Settings2 className="w-4 h-4 text-cyan-400" />
              <h3 className="text-sm font-bold text-white">YAML Parameter Controls</h3>
            </div>

            {/* Presets */}
            <div className="flex items-center gap-1">
              <button
                onClick={() => applyPreset('default')}
                className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-[10px] font-mono text-slate-300 transition-colors"
              >
                Default
              </button>
              <button
                onClick={() => applyPreset('gaming')}
                className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-[10px] font-mono text-slate-300 transition-colors"
              >
                Gaming
              </button>
              <button
                onClick={() => applyPreset('streaming')}
                className="px-2 py-1 rounded bg-slate-800 hover:bg-slate-700 text-[10px] font-mono text-slate-300 transition-colors"
              >
                Streaming
              </button>
            </div>
          </div>

          <div className="space-y-4 text-xs">
            {/* Tunnel Section */}
            <div className="space-y-2">
              <span className="font-mono text-[11px] text-cyan-400 font-semibold uppercase tracking-wider">
                [tunnel] Section
              </span>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-400 block mb-1">Tunnel Device Name</label>
                  <input
                    type="text"
                    value={tunnelName}
                    onChange={e => setTunnelName(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">MTU (Bytes)</label>
                  <input
                    type="number"
                    value={mtu}
                    onChange={e => setMtu(parseInt(e.target.value) || 1500)}
                    min={576}
                    max={9000}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">IPv4 CIDR Gateway</label>
                  <input
                    type="text"
                    value={ipv4}
                    onChange={e => setIpv4(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">IPv6 CIDR Gateway</label>
                  <input
                    type="text"
                    value={ipv6}
                    onChange={e => setIpv6(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
              </div>
            </div>

            {/* SOCKS5 Section */}
            <div className="space-y-2 pt-2 border-t border-slate-800/80">
              <span className="font-mono text-[11px] text-emerald-400 font-semibold uppercase tracking-wider">
                [socks5] Section
              </span>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-400 block mb-1">Local Daemon SOCKS5 Port</label>
                  <input
                    type="number"
                    value={socks5Port}
                    onChange={e => setSocks5Port(parseInt(e.target.value) || 10808)}
                    min={1024}
                    max={65535}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">Proxy Listen Address</label>
                  <input
                    type="text"
                    value={socks5Address}
                    onChange={e => setSocks5Address(e.target.value)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">UDP Relay Strategy</label>
                  <select
                    value={socks5Udp}
                    onChange={e => setSocks5Udp(e.target.value as any)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  >
                    <option value="udp">udp (Standard UDP ASSOCIATE)</option>
                    <option value="tcp">tcp (Encapsulated inside TCP)</option>
                  </select>
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">SO_MARK (fwmark)</label>
                  <input
                    type="number"
                    value={socks5Mark}
                    onChange={e => setSocks5Mark(parseInt(e.target.value) || 0)}
                    min={0}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
              </div>
            </div>

            {/* Misc Section */}
            <div className="space-y-2 pt-2 border-t border-slate-800/80">
              <span className="font-mono text-[11px] text-purple-400 font-semibold uppercase tracking-wider">
                [misc] Coroutine & System Limits
              </span>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-slate-400 block mb-1">Fiber Stack Size (Bytes)</label>
                  <input
                    type="number"
                    value={stackSize}
                    onChange={e => setStackSize(parseInt(e.target.value) || 81920)}
                    step={4096}
                    min={16384}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">Connect Timeout (ms)</label>
                  <input
                    type="number"
                    value={connectTimeout}
                    onChange={e => setConnectTimeout(parseInt(e.target.value) || 5000)}
                    step={500}
                    min={500}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">Read/Write Timeout (ms)</label>
                  <input
                    type="number"
                    value={rwTimeout}
                    onChange={e => setRwTimeout(parseInt(e.target.value) || 60000)}
                    step={5000}
                    min={5000}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  />
                </div>
                <div>
                  <label className="text-slate-400 block mb-1">Log Level</label>
                  <select
                    value={logLevel}
                    onChange={e => setLogLevel(e.target.value as any)}
                    className="w-full bg-slate-950 border border-slate-800 rounded-lg px-3 py-1.5 font-mono text-white focus:border-cyan-500 outline-none"
                  >
                    <option value="debug">debug</option>
                    <option value="info">info</option>
                    <option value="warn">warn</option>
                    <option value="error">error</option>
                  </select>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Right: Live YAML Preview and C Engine Log Stream */}
        <div className="lg:col-span-6 space-y-4">
          {/* YAML Viewer */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-xl flex flex-col">
            <div className="p-3 bg-slate-950 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2 font-mono text-xs text-slate-300">
                <FileCode className="w-4 h-4 text-cyan-400" />
                <span className="font-semibold text-white">hev_tunnel_config.yaml</span>
                {isValidConfig ? (
                  <span className="flex items-center gap-1 text-[10px] text-emerald-400 bg-emerald-500/10 px-2 py-0.5 rounded-full border border-emerald-500/20">
                    <ShieldCheck className="w-3 h-3" /> Valid YAML
                  </span>
                ) : (
                  <span className="flex items-center gap-1 text-[10px] text-rose-400 bg-rose-500/10 px-2 py-0.5 rounded-full border border-rose-500/20">
                    <AlertTriangle className="w-3 h-3" /> Check Bounds
                  </span>
                )}
              </div>

              <div className="flex items-center gap-2">
                <button
                  onClick={handleCopyYaml}
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-mono transition-colors border border-slate-700"
                >
                  {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>
                <button
                  onClick={handleDownloadYaml}
                  className="flex items-center gap-1 px-2.5 py-1 rounded bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold text-xs font-mono transition-colors"
                >
                  <Download className="w-3 h-3" />
                  <span>Download</span>
                </button>
              </div>
            </div>

            <div className="p-4 bg-slate-950 font-mono text-xs text-slate-200 overflow-x-auto select-text leading-relaxed">
              <pre>{yamlContent}</pre>
            </div>
          </div>

          {/* C Engine Log Output */}
          <div className="bg-slate-950 border border-slate-800 rounded-xl overflow-hidden shadow-xl">
            <div className="px-3 py-2 bg-slate-900 border-b border-slate-800 flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs font-mono text-slate-300">
                <Terminal className="w-3.5 h-3.5 text-cyan-400" />
                <span>libhev-socks5-tunnel.so Log Output</span>
              </div>
              <span className="text-[10px] font-mono text-slate-500">
                {isRunning ? 'Live streaming' : 'Idle'}
              </span>
            </div>

            <div className="p-3 font-mono text-[11px] text-slate-400 space-y-1 max-h-48 overflow-y-auto bg-slate-950">
              {logs.map((log, i) => (
                <div key={i} className="flex items-start gap-2">
                  <span className="text-slate-600 select-none">&gt;</span>
                  <span className={log.includes('TCP') ? 'text-cyan-300' : log.includes('UDP') ? 'text-purple-300' : 'text-slate-300'}>
                    {log}
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Coroutine Architecture Flow Card */}
      <div className="p-5 rounded-xl bg-slate-900/60 border border-slate-800 space-y-3">
        <h3 className="text-sm font-bold text-white flex items-center gap-2">
          <Cpu className="w-4 h-4 text-cyan-400" />
          Zero-Copy Coroutine Architecture Pipeline
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-3 text-xs">
          <div className="p-3 bg-slate-950 rounded-lg border border-slate-800/80 space-y-1">
            <div className="text-[10px] font-mono text-emerald-400 font-bold uppercase">1. Android TUN FD</div>
            <p className="text-slate-400 text-[11px]">
              VpnService passes Linux file descriptor into JNI <code className="text-cyan-300">nativeInit()</code>. Set non-blocking with <code className="text-slate-300">O_NONBLOCK</code>.
            </p>
          </div>

          <div className="p-3 bg-slate-950 rounded-lg border border-slate-800/80 space-y-1">
            <div className="text-[10px] font-mono text-cyan-400 font-bold uppercase">2. Epoll Reactor</div>
            <p className="text-slate-400 text-[11px]">
              <code className="text-cyan-300">hev_task_system</code> watches TUN and sockets using Linux epoll. Wakes only when packets arrive, saving battery.
            </p>
          </div>

          <div className="p-3 bg-slate-950 rounded-lg border border-slate-800/80 space-y-1">
            <div className="text-[10px] font-mono text-purple-400 font-bold uppercase">3. SOCKS5 Relay</div>
            <p className="text-slate-400 text-[11px]">
              IP packets are parsed in C. TCP connections issue SOCKS5 CONNECT; UDP datagrams encapsulate into UDP ASSOCIATE relay on 127.0.0.1:10808.
            </p>
          </div>

          <div className="p-3 bg-slate-950 rounded-lg border border-slate-800/80 space-y-1">
            <div className="text-[10px] font-mono text-amber-400 font-bold uppercase">4. Subprocess Daemon</div>
            <p className="text-slate-400 text-[11px]">
              The active protocol engine (Xray, Hysteria2, NaiveProxy, Shadowsocks) encrypts traffic with REALITY/Salamander and routes to censorship-free web.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
